# Generated by Django 3.0.3 on 2020-07-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200714_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date_created',
        ),
    ]
