# Generated by Django 3.0.3 on 2020-07-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_file_living_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='living_time',
            new_name='death_time',
        ),
    ]
